use_frameworks!

target 'EMStore_Example' do
  pod 'EMStore', :path => '../'

  target 'EMStore_Tests' do
    inherit! :search_paths

    
  end
end

target 'EMStore_TV' do
    pod 'EMStore', :path => '../'
end
